In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1=Series([0,1,2],index=list('TUV'))
ser2=Series([3,4],index=list('XY'))

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1=DataFrame(np.random.randn(4,3),columns=list('XYZ'))
dframe2=DataFrame(np.random.randn(3,3),columns=list('YQX'))

In [12]:
dframe1

X         Y         Z
0 -0.896364  0.508356 -0.638264
1 -0.749560  0.236074  1.694571
2 -0.183628  0.052751 -0.146278
3 -0.961795  1.656083  0.574500

In [13]:
dframe2

Y         Q         X
0  1.080221 -0.963851  0.879735
1 -0.925056 -0.978533 -1.021497
2 -0.749942 -0.012976  0.051057

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.896364  0.508356 -0.638264
1       NaN -0.749560  0.236074  1.694571
2       NaN -0.183628  0.052751 -0.146278
3       NaN -0.961795  1.656083  0.574500
0 -0.963851  0.879735  1.080221       NaN
1 -0.978533 -1.021497 -0.925056       NaN
2 -0.012976  0.051057 -0.749942       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.896364  0.508356 -0.638264
1       NaN -0.749560  0.236074  1.694571
2       NaN -0.183628  0.052751 -0.146278
3       NaN -0.961795  1.656083  0.574500
4 -0.963851  0.879735  1.080221       NaN
5 -0.978533 -1.021497 -0.925056       NaN
6 -0.012976  0.051057 -0.749942       NaN