In [1]:
import numpy as np

In [2]:
arr=np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
arr=np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr1=np.load('myarray.npy')

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2=arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.savez('ziparray.npz',x=arr1,y=arr2) #saving multiple arrays

In [14]:
archive=np.load('ziparray.npz')

In [16]:
archive['x']

array([0, 1, 2, 3, 4])

In [17]:
archive['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr=np.array([[1,2,3],[4,5,6]])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [24]:
arr=np.loadtxt('mytextarray.txt',delimiter=',')

In [25]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])