In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A=np.random.randn(10)
A

array([-0.12590231, -0.33321909, -0.5624975 ,  1.08599882,  0.83639267,
        0.87410455, -1.09630911, -1.61793143,  0.27349522, -0.0325553 ])

In [6]:
B = np.random.randn(10)
B

array([ 0.33115856,  1.82963847, -0.72890631,  0.42938106, -0.08435572,
        0.15235802,  0.50178984, -1.11312669,  0.59193366,  0.00946173])

In [7]:
# Binary Functions
np.add(A,B)

array([ 0.20525625,  1.49641938, -1.29140381,  1.51537988,  0.75203695,
        1.02646257, -0.59451927, -2.73105812,  0.86542888, -0.02309358])

In [8]:
np.maximum(A,B)

array([ 0.33115856,  1.82963847, -0.5624975 ,  1.08599882,  0.83639267,
        0.87410455,  0.50178984, -1.11312669,  0.59193366,  0.00946173])

In [9]:
np.minimum(A,B)

array([-0.12590231, -0.33321909, -0.72890631,  0.42938106, -0.08435572,
        0.15235802, -1.09630911, -1.61793143,  0.27349522, -0.0325553 ])

In [11]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True